const express = require('express');
const mongoose = require('mongoose');
const User = mongoose.model('User');

const jwt = require('jsonwebtoken');
const router = express.Router();

//when router does a post request at signup, we should do the following
router.post('/signup', async (req, res)=> {
    const {email, password } = req.body;

    try{
        const user = new User({email, password});

        //code to generate jwt, _id is the unique id generated by mongooose
        const token = jwt.sign({userId : user._id}, 'MY_SECRET_KEY');
        await user.save();
        res.send({token});
    }catch (err) {
        //to send the error to user, 422 -> unporcessable content
        return res.status(422).send(err.message);
    }
    
});

//for signin
router.post('/signin', async (req, res) => {
    const {email, password} = req.body;

    if (!email || !password){
        return res.status(422).send({error: 'Must provide email and password'});
    }

    const user = await User.findOne({email});

    if (!user){
        return res.status(422).send({error: "Inavlid password or email"});
    }

    try {
        await user.comparePassword(password);
        const token = jwt.sign({userId: user._id}, 'MY_SECRET_KEY');
        res.send({token});
    }catch (err){
        return res.status(422).send({error: "Inavlid password or email"});
    }
    
});

module.exports = router;